from setuptools import find_packages, setup

setup(
    name='visaApplication',
    version='1.0.0',
    description='visa application app',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'alembic',
        'aniso8601',
        'bcrypt',
        'cffi',
        'click',
        'Flask',
        'Flask-Bcrypt',
        'Flask-Migrate',
        'flask-restplus',
        'Flask-Script',
        'Flask-SQLAlchemy',
        'Flask-Testing',
        'itsdangerous',
        'Jinja2',
        'jsonschema',
        'Mako',
        'MarkupSafe',
        'pycparser',
        'PyJWT',
        'python-dateutil',
        'python-editor',
        'pytz',
        'six',
        'SQLAlchemy',
        'Werkzeug',
        'pandas',
        'requests',
        'mysql-connector-python',
        'python-dotenv',
        'DrissionPage',
    ],
    entry_points={
        'console_scripts': [
            'run=run:main.run',
        ],
    },
)
